[package]
name = "chatbot"
version = "0.2.3"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "MIT"
description = "An extensible chatbot"
documentation = "https://chatbot.rs/chatbot/"
repository = "https://github.com/jwilm/chatbot"
keywords = ["chat", "bot", "extensible"]
readme = "README.md"

[[bin]]
doc = false
name = "chatbot"
path = "src/main.rs"

[dependencies]
abort_on_panic = "1.0.0"
regex = "~0.1"
hyper = "~0.5"
rustc-serialize = "~0.3"
slack = "~0.6"
getopts = "~0.2"
irc = "~0.8"
startuppong = "~0.1"
